### ISSUE TITLE
bug(minimise): minimise not functioning as expected when viewport not at top of page on load

### ISSUE THREAD

**Issue by jackhkmatthews** [thisissoon/angular-scroll-collapse#21]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
```

## Current behavior

sn-minimise class not applied correctly to nav element in repo example app when page loaded with viewport not at top of page.

## Expected behavior

sn-minimise class should be be applied as normal (e.g when page loaded with viewport at top of page)

## Environment

This repos demo app.

**Comment by mbarbuscio** [comment]
Came here for the same issue. +1

**Comment by marianobarbuscio** [comment]
@edoparearyee any chance this might get implemented?

**Comment by edoparearyee** [comment]
Hi @mbarbuscio thanks for using this library. Unfortunately we've been very busy recently so not had a chance to take a look at this yet. This should be fixed as it's a bug. Hopefully have a chance to look at it within the next week or so.

**Comment by edoparearyee** [comment]
I am unable to replicate this in the example app so closing for now. If someone can successfully replicate this issue I will reopen it.

**Comment by mbarbuscio** [comment]
Just tested this thorougly. Apparently, the component works fine if you add the (minimiseChange) event handler on the element that has the directive. If there is no event handler, when you navigate or refresh the page whatever is the current scroll will be taken as the initial position and not apply the minimise class.

**Comment by edoparearyee** [comment]
@mbarbuscio I tested this and found out this wasn't the issue. I was able to replicate this by turning on `OnPush` change detection instead.

Will get a fix out soon.
